/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

object Book {
    var title: String = "The Pragmatic Programmer: From Journeyman to Master"
    var authors: List<String> = listOf("Andrew Hunt", "David Thomas")
    var edition: Int = 1
}
